# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('born_at', models.DateField(blank=True)),
                ('died_at', models.DateField(blank=True, null=True)),
                ('img', models.ImageField(upload_to=b'images/')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followStatus', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('published_at', models.DateField(blank=True)),
                ('summary', models.CharField(max_length=600)),
                ('img', models.ImageField(upload_to=b'images/')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=b'images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.ManyToManyField(through='bookstore.AuthorFollow', to='bookstore.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('rateDate', models.DateField(default=0)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratingProfile', to='bookstore.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'not read'), (2, b'readed'), (3, b'wish')], default=1)),
                ('date', models.DateField(default=0)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statusProfile', to='bookstore.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='booksRating',
            field=models.ManyToManyField(related_name='booksRating', through='bookstore.Rating', to='bookstore.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='booksStatus',
            field=models.ManyToManyField(related_name='booksStatus', through='bookstore.Status', to='bookstore.Book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(to='bookstore.Category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Category'),
        ),
        migrations.AddField(
            model_name='book',
            name='profileRating',
            field=models.ManyToManyField(related_name='rating', through='bookstore.Rating', to='bookstore.Profile'),
        ),
        migrations.AddField(
            model_name='book',
            name='profileStatus',
            field=models.ManyToManyField(related_name='status', through='bookstore.Status', to='bookstore.Profile'),
        ),
        migrations.AddField(
            model_name='authorfollow',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Profile'),
        ),
        migrations.AddField(
            model_name='author',
            name='followedBy',
            field=models.ManyToManyField(through='bookstore.AuthorFollow', to='bookstore.Profile'),
        ),
    ]
