# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorfollow',
            name='followStatus',
            field=models.IntegerField(default=0),
        ),
    ]
