# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='profileStatus',
            field=models.ManyToManyField(related_name='status', through='bookstore.Status', to='bookstore.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='booksStatus',
            field=models.ManyToManyField(related_name='booksStatus', through='bookstore.Status', to='bookstore.Book'),
        ),
        migrations.AlterField(
            model_name='author',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='profileRating',
            field=models.ManyToManyField(related_name='rating', through='bookstore.Rating', to='bookstore.Profile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='booksRating',
            field=models.ManyToManyField(related_name='booksRating', through='bookstore.Rating', to='bookstore.Book'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratingProfile', to='bookstore.Profile'),
        ),
        migrations.AlterField(
            model_name='status',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statusProfile', to='bookstore.Profile'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.IntegerField(choices=[(1, 'not read'), (2, 'readed'), (3, 'wish')], default=1),
        ),
    ]
