# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 23:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('rateDate', models.DateField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
