# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_user_repassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repassword',
        ),
    ]
