# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20170428_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='profileRating',
            field=models.ManyToManyField(through='bookstore.Rating', to='bookstore.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='booksRating',
            field=models.ManyToManyField(through='bookstore.Rating', to='bookstore.Book'),
        ),
        migrations.AddField(
            model_name='rating',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Profile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book'),
        ),
    ]
