# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20170429_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'not read'), (2, 'readed'), (3, 'wish')], default=1)),
                ('date', models.DateField(default=0)),
                ('book', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Book')),
                ('profile', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookstore.Profile')),
            ],
        ),
    ]
