# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_book_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
