# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_auto_20170425_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
