# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_auto_20170424_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='bookstore/templates/pics/'),
        ),
    ]
